# Generated by Django 2.2.1 on 2019-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
